services:
  api-solid-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apisolid

# é necessário abrir o docker desktop antes (pode fechar)
# docker compose start para iniciar
# caso o banco tenha sido deletado, npx prisma migrate dev